routes/web.php
<?php

use Sautor\Contests\Controllers\ContestController;
use Sautor\Contests\Controllers\EntryController;
use Sautor\Contests\Controllers\PublicController;

Sautor\groupRoute(function () {
    Route::middleware('addon:contests')->name('contests.')->prefix('contests')->group(function () {
        Route::get('/', [PublicController::class, 'index'])->name('public.index');

        Route::resource('contests', ContestController::class)->middleware('auth');

        Route::get('{contest}', [PublicController::class, 'show'])->name('public.show');
        Route::get('{contest}/inscrever', [PublicController::class, 'register'])->name('public.register');

        Route::get('entries/{entry}', [EntryController::class, 'show'])->middleware('auth')->name('entries.show');

    });
});

resources/views/contests/create.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <header class="group-page__header">
        <h1 class="group-page__header__title">
            Criar concurso
        </h1>
    </header>

    @php($scope = 'new-contest')
    <form action="{{ $grupo->route('contests.contests.store') }}" method="POST" enctype="multipart/form-data" data-vv-scope="{{ $scope }}">
        @csrf

        @include('contests::contests.form')

        <div class="sautor-addon__actions">
            <button type="submit" class="button button--primary">Criar</button>
        </div>
    </form>
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/contests/styles.css') }}">
@endpush

resources/views/contests/edit.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <header class="group-page__header">
        <h1 class="group-page__header__title">
            Editar concurso
        </h1>
    </header>

    @php($scope = 'edit-contest')
    <form action="{{ $grupo->route('contests.contests.update', $contest) }}" method="POST" data-vv-scope="{{ $scope }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        @include('contests::contests.form')

        <div class="sautor-addon__actions">
            <button type="submit" class="button button--primary">Editar</button>
            @can('delete', $contest)
                <button type="button" class="button button--danger-light" @click.prevent="openModal('deleteModal')">
                    <span class="far fa-trash mr-2"></span>
                    Eliminar
                </button>
            @endcan
        </div>
    </form>

    @can('delete', $contest)
        <modal id="deleteModal">
            <div class="modal__body modal__confirmation">
                <div class="modal__confirmation__icon">
                    <span class="fas fa-exclamation"></span>
                </div>
                <div class="modal__confirmation__content">
                    <h3 class="modal__confirmation__title">Eliminar concurso</h3>
                    <p class="modal__confirmation__text">
                        Tem a certeza que quer eliminar o concurso <strong>{{ $contest->name }}</strong>?
                    </p>
                </div>
            </div>
            <form class="modal__footer" method="POST" action="{{ $contest->grupo->route('contests.contests.destroy', $contest) }}">
                @csrf
                @method('DELETE')
                <button type="submit" class="button button--danger">Eliminar</button>
                <button type="button" class="button" @click.prevent="closeModal('deleteModal')">Cancelar</button>
            </form>
        </modal>
    @endcan
@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/contests/styles.css') }}">
@endpush

resources/views/contests/form.blade.php
<div class="s-cts-grid s-cts-grid-cols-1 md:s-cts-grid-cols-2 s-cts-gap-x-8">
    <div class="lg:s-cts-col-span-2">
        <x-forms.input
                name="name"
                label="Nome"
                :value="isset($contest) ? $contest->name : null"
                required
                :scope="$scope"
        />
    </div>

    <x-forms.input name="open_at" label="Abrir inscrições a" :value="isset($contest) ? $contest->open_at : null"
                   type="datetime-local" :scope="$scope"/>
    <x-forms.input name="close_at" label="Fechar inscrições a" :value="isset($contest) ? $contest->close_at : null"
                   type="datetime-local" :scope="$scope"/>

    <x-forms.input name="voting_open_at" label="Abrir votação a" :value="isset($contest) ? $contest->voting_open_at : null"
                   type="datetime-local" :scope="$scope"/>
    <x-forms.input name="voting_close_at" label="Fechar votação a" :value="isset($contest) ? $contest->voting_close_at : null"
                   type="datetime-local" :scope="$scope"/>

    @foreach(['opening_text' => 'Texto de abertura', 'disclaimer' => 'Aviso', 'thankyou_text' => 'Mensagem de agradecimento'] as $key => $label)
        <div class="field">
            <label class="label">{{ $label }}</label>
            <div class="control">
                <small-content-editor name="{{ $key }}"
                                      value="{{ isset($contest) ? $contest->{$key} : null }}"
                                      simple></small-content-editor>
            </div>
        </div>
    @endforeach

    <x-forms.input
            name="origin_label"
            label="Etiqueta do campo de 'origem'"
            :value="isset($contest) ? $contest->origin_label : null"
            :scope="$scope"
    />

    <div>
        <h4 class="title title--xs s-cts-mb-3">Outras opções</h4>
        <x-forms.checkbox name="accept_text" label="Aceitar texto" :value="isset($contest) ? $contest->accept_text : null" :scope="$scope" />
        <x-forms.checkbox name="accept_images" label="Aceitar imagens" :value="isset($contest) ? $contest->accept_images : null" :scope="$scope" />
        <x-forms.checkbox name="show_at_home" label="Mostrar na página inicial" :value="isset($contest) ? $contest->show_at_home : null" :scope="$scope" />
        <x-forms.file name="banner" label="Banner" accept=".png,.jpg,.jpeg"
                      rules="ext:png,jpg,jpeg" :scope="$scope" />
    </div>
</div>

resources/views/contests/grid-component.blade.php
@unless($contests->isEmpty())
    <section class="s-cts-grid md:s-cts-grid-cols-2 lg:s-cts-grid-cols-3 s-cts-gap-4">
        @foreach($contests as $contest)
            <article class="s-cts-bg-white s-cts-rounded-lg s-cts-shadow s-cts-flex s-cts-flex-col s-cts-overflow-hidden">
                <div
                        class="s-cts-aspect-[2/1] s-cts-bg-cover s-cts-bg-center s-cts-relative @if($contest->getMedia('banner')->isEmpty()) s-cts-bg-gray-200 s-cts-text-gray-400 s-cts-text-6xl s-cts-flex s-cts-justify-center s-cts-items-center @endif"
                        @if($contest->getMedia('banner')->isNotEmpty()) style="background-image: url({{$contest->getFirstMediaUrl('banner')}});" @endif
                >
                    @if($contest->getMedia('banner')->isEmpty())
                        @if(isset($contest->grupo) and ($contest->grupo->icon ?? $contest->grupo->logo))
                            <img src="{{ $contest->grupo->icon ?? $contest->grupo->logo }}" class="s-cts-w-auto s-cts-h-auto s-cts-object-contain s-cts-max-w-[50%] s-cts-max-h-[70%] s-cts-grayscale s-cts-opacity-[15%]">
                        @else
                            <x-icon icon="award" class="s-cts-w-1/3 s-cts-h-3/4 s-cts-fill-current" />
                        @endif
                    @endif
                </div>
                <div class="s-cts-px-4 s-cts-py-3 s-cts-flex-1 s-cts-flex s-cts-flex-col">
                    <h3 class="s-cts-font-headline s-cts-text-xl">
                        <a href="{{ $contest->grupo->route('contests.public.show', $contest) }}" class="s-cts-text-primary-500 hover:s-cts-text-primary-600">{{ $contest->name }}</a>
                    </h3>
                </div>
            </article>
        @endforeach
    </section>
@else
    <section class="sautor-list--empty tags-list--empty">
        {{ empty($empty_message) ? 'Não existem concursos.' : $empty_message }}
    </section>
@endunless

resources/views/contests/index.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <div class="group-page__header">
        <h1 class="group-page__header__title">
            Concursos
        </h1>

        <div class="group-page__header__actions">
            <a href="{{ $grupo->route('contests.contests.create') }}" class="button button--responsive">
                <span class="far fa-plus"></span>
                Novo concurso
            </a>
        </div>
    </div>

    @include('contests::contests.list-component', ['actions' => fn ($tc) => [
        ['label' => 'Editar', 'icon' => 'fas fa-pencil', 'link' => $tc->grupo->route('contests.contests.edit', $tc)]
    ]])

@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/contests/styles.css') }}">
@endpush

resources/views/contests/list-component.blade.php
@unless($contests->isEmpty())
    <section class="sautor-list sheets-list">
        @foreach($contests as $contest)
            <div class="sautor-list__item">
                <div class="sautor-list__item__logo">
                    <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
                        <span class="fad fa-award fa-swap-opacity"></span>
                    </span>
                </div>
                <a href="{{ $contest->grupo->route('contests.contests.show', $contest) }}" class="sautor-list__item__data">
                    <p class="sautor-list__item__name">
                        {{ $contest->name }}
                    </p>
                    <p class="sautor-list__item__meta">
    {{ $contest->entries->count() }} inscrições
    @if($contest->isVotingOpen)
        <span class="badge badge--success">Votação aberta</span>
    @elseif($contest->isVotingClosed)
        <span class="badge badge--danger">Votação fechada</span>
    @elseif($contest->isOpen)
        <span class="badge badge--success">Inscrições abertas</span>
    @elseif($contest->isClosed)
        <span class="badge badge--danger">Inscrições fechadas</span>
    @else
        <span class="badge">Por abrir</span>
    @endif
</p>
</a>

<div class="sautor-list__item__actions">
@unless(empty($actions) or empty($a = $actions($contest)))
    @foreach($a as $action)
        <a title="{{ $action['label'] }}"
           @if(!empty($action['link']))
               href="{{ $action['link'] }}"
           @elseif(!empty($action['modal']))
               href="#" data-toggle="modal" data-target="#{{ $action['modal'] }}"
                @endif
        >
            <span class="{{ $action['icon'] }}"></span>
        </a>
    @endforeach
@endunless
<a title="Ver" href="{{ $contest->grupo->route('contests.contests.show', $contest) }}">
    <span class="far fa-angle-right"></span>
</a>
</div>
</div>
@endforeach
</section>
@else
<section class="sautor-list--empty tags-list--empty">
{{ empty($empty_message) ? 'Não existem concursos.' : $empty_message }}
</section>
@endunless

resources/views/contests/show.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <div class="group-page__header">
        <h1 class="group-page__header__title">
            {{ $contest->name }}
            <small>{{ $contest->entries_count }} testemunhos</small>
        </h1>

        <div class="group-page__header__actions">
            <a href="{{ $grupo->route('contests.contests.edit', $contest) }}" class="button button--responsive">
                <span class="fas fa-pencil"></span>
                Editar
            </a>
        </div>
    </div>


    @include('contests::entries.list-component')

    {!! $entries->links() !!}

@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/contests/styles.css') }}">
@endpush

resources/views/entries/list-component.blade.php
@unless($entries->isEmpty())
    <section class="sautor-list sheets-list">
        @foreach($entries as $entry)
            <div class="sautor-list__item">
                <div class="sautor-list__item__logo">
                    @if($entry->hasMedia('images'))
                        <img src="{{ $entry->getFirstMediaUrl('images') }}" class="cover">
                    @else
                    <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
                        <span class="fad fa-award"></span>
                    </span>
                    @endif
                </div>
                <a href="{{ $entry->contest->grupo->route('contests.entries.show', $entry) }}" class="sautor-list__item__data">
                    <p class="sautor-list__item__name">
                        {{ $entry->name }}
                    </p>
                    <p class="sautor-list__item__meta">
                        {{ $entry->origin }}

                        @if($entry->hasMedia('images'))
                            &middot; <span class="far fa-images"></span> {{ $entry->getMedia('images')->count() }}
                        @endif
                    </p>
                </a>

                <div class="sautor-list__item__actions">
                    @unless(empty($actions) or empty($a = $actions($collection)))
                        @foreach($a as $action)
                            <a title="{{ $action['label'] }}"
                               @if(!empty($action['link']))
                                   href="{{ $action['link'] }}"
                               @elseif(!empty($action['modal']))
                                   href="#" data-toggle="modal" data-target="#{{ $action['modal'] }}"
                                    @endif
                            >
                                <span class="{{ $action['icon'] }}"></span>
                            </a>
                        @endforeach
                    @endunless
                    <a title="Ver" href="{{ $entry->contest->grupo->route('contests.entries.show', $entry) }}">
                        <span class="far fa-angle-right"></span>
                    </a>
                </div>
            </div>
        @endforeach
    </section>
@else
    <section class="sautor-list--empty tags-list--empty">
        {{ empty($empty_message) ? 'Não existem inscrições.' : $empty_message }}
    </section>
@endunless

resources/views/entries/show.blade.php
@extends('layouts.group-admin')

@section('group-content')
    <div class="group-page__header">
        <h1 class="group-page__header__title">
            Participação #{{ $entry->id }}
            <small>{{ $entry->contest->name }}</small>
        </h1>
    </div>

    <div class="people-show__tab__card">
        <p class="people-show__item">
            <span class="people-show__item__label">Nome</span>
            {{ $entry->name }}
        </p>

        @unless(empty($entry->contest->origin_label))
        <p class="people-show__item">
            <span class="people-show__item__label">{{ $entry->contest->origin_label }}</span>
            {{ $entry->origin }}
        </p>
        @endunless

        <div class="people-show__item">
            <span class="people-show__item__label">Carregado por</span>
            @empty($entry->pessoa)
                <span class="people-show__item__empty">IP: {{ $entry->ip }} (sem sessão iniciada)</span>
            @else
                <x-people.show :person="$entry->pessoa" :meta="'IP:'.$entry->ip" />
            @endempty
        </div>
    </div>

    @unless(empty($entry->content))
        <header class="people-show__tab__header">
            <h2 class="people-show__tab__title">Conteúdo</h2>
        </header>
        <div class="prose s-cts-whitespace-pre-line s-cts-mb-8 s-cts-italic s-cts-font-accent s-cts-text-gray-700">{!! $entry->content !!}</div>
    @endunless

    @unless(empty($entry->notes))
        <header class="people-show__tab__header">
            <h2 class="people-show__tab__title">Notas</h2>
        </header>
        <div class="prose s-cts-whitespace-pre-line s-cts-mb-8 s-cts-italic s-cts-font-accent s-cts-text-gray-700">{!! $entry->notes !!}</div>
    @endunless

    @if($entry->hasMedia('images'))
        <header class="people-show__tab__header">
            <h2 class="people-show__tab__title">Imagens</h2>
        </header>

        <div class="s-cts-grid s-cts-grid-cols-3 md:s-cts-grid-cols-4 lg:s-cts-grid-cols-5 xl:s-cts-grid-cols-6 s-cts-gap-4">
            @foreach($entry->getMedia('images') as $image)
                <a href="{{ $image->getUrl() }}" target="_blank">
                    <img src="{{ $image->getUrl() }}" class="s-cts-w-full s-cts-aspect-square s-cts-rounded s-cts-object-cover s-cts-border s-cts-border-gray-300" >
                </a>
            @endforeach
        </div>
    @endif

@endsection

@push('styles')
    <link rel="stylesheet" href="{{ asset('addons/contests/styles.css') }}">
@endpush

resources/views/livewire/register-form.blade.php
<div>
    <h1 class="group-page__title">
        Inscrever
        <br /><small>{{ $contest->name }}</small>
    </h1>

    @if ($isSaved)
        <div class="s-cts-max-w-prose s-cts-mx-auto">
            <div class="alert alert--success">
                <p>
                    Inscrição recebida com sucesso!
                </p>
            </div>

            <div class="prose lg:prose-lg empty:s-cts-hidden s-cts-mx-auto s-cts-mt-8">
                {!! $contest->thankyou_text !!}
            </div>
        </div>
    @else
        <div class="max-w-prose mx-auto">

            <x-forms.input name="name" label="Nome" required :options="['wire:model' => 'name']"/>

            @unless(empty($contest->origin_label))
                <x-forms.input name="origin" :label="$contest->origin_label" required
                               :options="['wire:model' => 'origin']"/>
            @endunless

            @if($contest->accept_text)
                <div class="field @if($errors->has('content')) field--invalid @endif">
                    <label for="content" class="label">
                        Conteúdo
                    </label>
                    <div class="s-cts-mt-2 s-cts-grid" x-data="{ content: '' }">
                        <div class="input s-cts-py-2 s-cts-px-3 s-cts-text-base s-cts-whitespace-pre-wrap"
                             style="visibility: hidden; grid-area: 1/1/2/2;" x-html="content">
                        </div>
                        <textarea name="content" id="content" x-model="content" wire:model="content"
                                  class="input s-cts-min-h-[10rem] s-cts-resize-none"
                                  style="grid-area: 1/1/2/2;"></textarea>
                    </div>
                    @if ($errors->has('content'))
                        <span class="field__help field__help--invalid">
                            {{ $errors->first('content') }}
                        </span>
                    @endif
                </div>
            @endif


            @if($contest->accept_images)

                <x-forms.file name="images" label="Imagens" accept="image/*" multiple
                              :options="['wire:model' => 'images']"/>

                <div class="s-cts-grid s-cts-grid-cols-4 s-cts-gap-4">
                    @foreach($images as $image)
                        <img src="{{ $image->temporaryUrl() }}"
                             class="s-cts-w-full s-cts-aspect-square s-cts-rounded s-cts-object-cover s-cts-border s-cts-border-gray-300">
                    @endforeach
                </div>

            @endif


            <div class="prose empty:s-cts-hidden s-cts-mx-auto s-cts-mb-8 empty:s-cts-hidden">
                {!! $contest->disclaimer !!}
            </div>

            <x-forms.checkbox name="consent"
                              :label="'Eu dou o meu consentimento ao uso desta participação por '.$contest->grupo->nome.' de '.config('app.name').'.'"
                              :options="['wire:model' => 'consent']"/>

            <div class="s-cts-flex s-cts-justify-end s-cts-mt-8">
                <button type="button" class="button button--primary" wire:click="save" wire:loading.attr="disabled">
                        <span wire:loading>
                            A enviar...
                        </span>
                    <span wire:loading.remove>
                            Enviar
                        </span>
                </button>
            </div>

        </div>
    @endif

</div>